### ISSUE TITLE
Question - HD textures

### ISSUE THREAD

**Issue by heroesiiifan** [mapron/FreeHeroes#1]
Hello,

Please keep following the project! It looks very good. 😊
I hope the project doesn't fall asleep and maybe other developers will join.

I am really unhappy about the state of VCMI. 😕

Do you think it will be possible to load higher resolution textures (from the official HD) in the future?
So a kind of texture pack support. Textures that are not available in high resolution can either be added by fans or scaled up using xBRZ, for example.

To create the hd version that Heroes III really deserves.

Unfortunately my c/c++ skills are not sufficient to assist in a game development.

**Comment by mapron** [comment]
> Do you think it will be possible to load higher resolution textures (from the official HD) in the future?

yeah, I did such an experiment: created 4x upscaled Titan sprite with NN, and set 200% Windows scale. It worked just fine (did not check how it well scales/perfomance).
So, in short, it already ready for hidpi for battle window.

But, it do not automagically will use hidpi in every UI element, so still a lot of work to do (I at least want to double resolution eveywhere work fine).

And yet, that was all about technical answer.
I'm not sure if I support importing textures from Ubi HD, if that also bring new copyright challenges.

**Comment by mapron** [comment]
> Unfortunately my c/c++ skills are not sufficient to assist in a game development.

I do not need new C++ developers right now, I need more testers/motivators, who write me and ask:
"Hey! Where are new features? When battle features all finihsed? when you start adventure map? I'm waitiing" and so on :)

**Comment by mapron** [comment]
>   I hope the project doesn't fall asleep and maybe other developers will join.
  
  I hope too. I was stale for an year (I have some personal issues). Now I work on it VERY partial-time (like, 1 day/month). Current goal - finish all game mechanics related to battle (won't return again except gazillion bugfixes in the future). 
  After that - continue work ion adventure map (at this point it only my local branch with only hero sprite moving and that's it)

**Comment by mapron** [comment]
Also , looks like you from German, right? I also would appreciate translations contribution ;)

**Comment by mapron** [comment]
I have updated my bio text, added Discord-id there, if you wish to ask something more, you're always welcome to ask in person!

**Comment by heroesiiifan** [comment]
Hey! Where are new features? 😀

A possibility to activate hidpi in the future would be great. But i think there are more important things first. 😀

Actually, in terms of copyright, it shouldn't make any difference whether the end user extracts the files from Heroes III Complete or Heroes III HD. The rights are held by UBI anyway.

Yes, of course i would support a german translation. but it would be best to do it when there are not so many changes in the texts for the time being.

**Comment by mapron** [comment]
> Yes, of course i would support a german translation. but it would be best to do it when there are not so many changes in the texts for the time being.

No problem. Also, I understand lack of motivation to do so in half-finished (ok, 5%-finished tbh) project.
Just to clarify - I don't think there is any reason to wait for translation of game objects (units etc) - they won't change anyway. If there will be format file change for translation - it's only developer problem.
At least I would appreciate to test things - add a few lines here and there and look if there are any problems.
You know, German have longer lines in average than Russian and English - so it's a common problem to have text crop wherever it goes. 

Besides, thanks again for your interest, that motivates me to spent more that 1day/1month for this project. I hope.
