### ISSUE TITLE
Lua API for modding?

### ISSUE THREAD

**Issue by JeffRockatansky** [mapron/FreeHeroes#13]
Might be useful to achieve more modding flexibility than the VCMI modding has.

**Comment by mapron** [comment]
I have lua api for modding in some parts. Where exactly you want to see it? 
See spells and skills, artifacts  - they already customized with Lua.

**Comment by mapron** [comment]
```
]},
"sod.skill.armourer"        : {  "calc": [
    "values = { 5, 10, 15 } ",
    "bonus =  values[skillLevel + 1]",
    "if isSpec then bonus = bonus + math.ceil(bonus * heroLevel / 20) end",
    "h.defense:set(bonus, 100)"
]},
```

**Comment by JeffRockatansky** [comment]
That's cool. Didn't see any reference to it in the main docs. Will dive into it a bit more then.

**Comment by mapron** [comment]
Well, I though if I mention Lua and Sol as dependencies on the main page, you can guess it used for scripting somewhere... 

I know docs are pretty horrible for now, sorry about that.

**Comment by mapron** [comment]
You can search for `"calc"` text over json files, to see places where Lua already used.

**Comment by mapron** [comment]
Also please not that I have a few game parts finished (mostly regarding map H3M format or sprites or another low-level stuff). Modding (well, configuration?) is still in the development - and first priority is to be feature-complete, then extend it with scripts. Sometimes I see that Lua is beneficial from the start - as I did for "calc" formulas.
