### ISSUE TITLE
Improve HotA map parsing

### ISSUE THREAD

**Issue by ProgerXP** [mapron/FreeHeroes#16]
In response to https://github.com/HeroWO-js/h3m2json/issues/1, you may want to check the following aspects of your parser (I will not *write code for you* but you can infer the details from this diff: https://github.com/HeroWO-js/h3m2json/commit/25ddef27f1ea0678578b61710f9d37bce6120d2c):

- Checks like `format >= MapFormat::HOTA1` are invalid and misleading given that WoG/VCMI format numbers are higher
- New victory condition types: 
  - 11: defeat all monsters: two uint8 (allow normal victory, apply to computer)
  - 12: survive for given time: as above plus uint16 (1-based number of days)
- New quest type: 10 - uint32 subclass; if 0, require specific hero class (uint32 class count followed by bitfield with length of `ceil(count/8)`); if 1, return after specific date (uint32 0-based date)
- New options for picking random town alignment, in addition to 0xFF (same as owner) and 0-7 (same as Player N): 8-15: different from Player N.
- Seer Hut quest counts work as follows: uint32 one-time quest count, then array of the usual quest structures, then uint32 recurring quest count, then the same array again (the sum of both counts cannot be 0)

**Comment by mapron** [comment]
Thanks, that is very handful. I appreciate your help!

**Comment by mapron** [comment]
@ProgerXP  I fixed binary level for all hota/sod complete maps in master. About those version check stuff, yeah, I was thinking about mor robust version struct for that purpose, probably will fix later.

**Comment by mapron** [comment]
Thank you again, your diff was very helpful.
