### ISSUE TITLE
Native support for macOS

### ISSUE THREAD

**Issue by smnbbrv** [mapron/FreeHeroes#17]
Hi, a great idea and I hope it lands well.

Currently HotA requires wine / parallels to run on non-windows platforms. Is this going to be finally fixed in this project? 

Thanks for the work you are doing

**Comment by mapron** [comment]
@smnbbrv  I have no testing macOS machine, but current master should compile for Linux and Windows. And run. and play.

So no real reason for no macOS support except proper testing + bunch of build scripts linke bundle installation and so on. If you have macOS developer setup, you can check out what am I missing in CMake atm.

Nothing really platfrom-specific in my project - except windows registry lookup to find HotA installation on Windows host (that is optional and just for convenience).

**Comment by mapron** [comment]
And HotA conparison is unfair (as it has not source code etc), fair is comparison to https://github.com/vcmi/ (and VCMI project is far ahead of FH, except HotA support probablty. And good RMG. That's it)
