### ISSUE TITLE
Issues with Linux

### ISSUE THREAD

**Issue by heroesiiifan** [mapron/FreeHeroes#2]
### Environment
**Used OS:** latest Manjaro

**Compiled with:**
```
sudo pacman -Syu
sudo pacman -Sy
sudo pacman -S git cmake ffmpeg qt5-base qt5-doc qt5-multimedia qt5-tools base-devel

git clone https://github.com/mapron/FreeHeroes
cd FreeHeroes/
cmake .
make
```

### Issues
- folder "assetcompiled/Translations" must be created by hand
- tests failed (and must be commented out in CMakeLists.txt)
- converter have problems with upper/lowercase (had to rename "Mp3" to "MP3")
- .bat file works on Win only (but I can do manually: "cmake -DLUPDATE_TOOL=lupdate -P ../cmake/translationsRelease.cmake")

but basically it's working on linux.

**Comment by mapron** [comment]
> .bat file works on Win only 
that's intended. I also do run translationsRelease same way on Linux. 
For other parts - thanks, I will look into it, that's been a while I've tested everything from scratch (last couple times just a compilation).

**Comment by mapron** [comment]
I can create shell file with same command, probably a good idea to save couple of seconds. (you should not copy text from batch I think).

**Comment by mapron** [comment]
I tried to fixed everything, but I don't get something.
"assetcompiled/Translations" creating just fine for me; using cmake 3.21 at the moment tho. Could you specify cmake version you have? Distrowatch tells me it's 3.21.2 on Manjaro now.

At what moment you need to create it? 
For me it works this way:
1. on cmake configure step, nothing in created in the build dir;
2. on build step, all_resources target creating resources (it also included in 'all').

Is it an issue for you that 'all_resources' target is not in deps for executables or what? 
Or you have explicit build error, qm creating failing?

**Comment by mapron** [comment]
So, @heroesiiifan  I tried to address evrything. Can you check again issue with directory, before and after commit a0941623c1a5cb1d78e0d365200972688cc540b2 - I want to understand - if that really was the core issue.

Other issues should be fixed in master as well.

**Comment by heroesiiifan** [comment]
> So, @heroesiiifan I tried to address evrything. Can you check again issue with directory, before and after commit [a094162](https://github.com/mapron/FreeHeroes/commit/a0941623c1a5cb1d78e0d365200972688cc540b2) - I want to understand - if that really was the core issue.
> 
> Other issues should be fixed in master as well.
After this commit it works.

Before I will get this error:
`[ 85%] Linking CXX executable BattleEmulator
[ 85%] Built target FHBattleEmulator
[ 85%] Generating assetsCompiled/Application.rcc
[ 85%] Generating assetsCompiled/Battle.rcc
[ 86%] Generating assetsCompiled/Translations/BattleEmulator_de_DE.qm
Updating '/home/heroesiiifan/FreeHeroes/assetsCompiled/Translations/BattleEmulator_de_DE.qm'...
lrelease error: cannot create '/home/heroesiiifan/FreeHeroes/assetsCompiled/Translations/BattleEmulator_de_DE.qm': No such file or directory
make[2]: *** [CMakeFiles/all_resources.dir/build.make:111: assetsCompiled/Translations/BattleEmulator_de_DE.qm] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:297: CMakeFiles/all_resources.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
`

**Comment by heroesiiifan** [comment]
> I tried to fixed everything, but I don't get something.
> "assetcompiled/Translations" creating just fine for me; using cmake 3.21 at the moment tho. Could you specify cmake version you have? Distrowatch tells me it's 3.21.2 on Manjaro now.
> 
> At what moment you need to create it?
> For me it works this way:
> 
>     1. on cmake configure step, nothing in created in the build dir;
> 
>     2. on build step, all_resources target creating resources (it also included in 'all').
> 
> 
> Is it an issue for you that 'all_resources' target is not in deps for executables or what?
> Or you have explicit build error, qm creating failing?

My Manjaro is on cmake 3.21.2

**Comment by mapron** [comment]
> Before I will get this error

now I get it. I always testing ninja build. So I guess this is the difference between ninja and make - ninja creates all required folders for output.

**Comment by mapron** [comment]
Thanks again for the assistance!
