### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by jxo** [mapron/FreeHeroes#4]
You have done a good job.
I also want to remake a homm3 game.
Util now, I only read HD version Pak file, deal with the textures, and draw it with opengl, sprite animation can be viewed. HD verison is good texture resource, has x2, x3 texture resources to use. The missing sprite can be redraw by Super Resolution Algorithm.
Qt is good for PC.
Is that a good choice for phone or pad with multitouch screen?

**Comment by mapron** [comment]
> The missing sprite can be redraw by Super Resolution Algorithm.
I wanna warn you it's not that easy (you need to deal with transparency for sprites, and superres network gave meh result for me. so... manual work is required).

Qt is ok for phon / tablet is has gestures and multitouch support.

However, if you want to have close to native UI and UX, you ought to move from Qt to some native framework.  If we talking about Qt Widgets.
If you choose Qt QML, it's fantastic for mobile but for desktop UI you will have a lot of extra work... no silver bullet as far as I know.

Also I have little mobile XP, so take this with grain of salt.

**Comment by mapron** [comment]
Any reason to NOT contribute to VCMI? it has mobile support already.

**Comment by mapron** [comment]
If you click on my github profile, you can find discord ID. It is much better then creating issues only for the conversation.

**Comment by jxo** [comment]
maybe on slack
discord is not work in China😂

**Comment by mapron** [comment]
@jxo  I am in Russia so I understand 'a lot of stuff do not work' . Slack is banned btw. well... you can continue here as you wish!

**Comment by jxo** [comment]
@mapron 
I pull the new codes, project has changed a lot.
But it can't be compiled on linux now on my laptop which runs Archlinux.
Perhaps you develop mainly on windows, have not tested on linux yet.
There are some problems that I encountered.
1. cmake command AddCompilerFlagIfSupported can't be found.
2. Mernel depends on 7zip_static, but 7zip_static uses windows.h
3. Some errors from clang-format, "format is not conforming to the current style" mostly on c++20 concepts.  My clang verison is 15.0.7
If you have the time and could help solve these small problems, it would be great.

**Comment by jxo** [comment]
![mmexport1677415184543](https://user-images.githubusercontent.com/1549577/221411004-5b95aeb0-b177-483b-b903-d8d6d2982ef6.png)
HD Sprite is much better

**Comment by mapron** [comment]
>  Perhaps you develop mainly on windows, have not tested on linux yet.

That how it goes, right, did not fix UNIX compilation yet since last tag in git. I burned one of my two PC's recently, so I stuck with Win machine for a while, need to make dualboot setup.

**Comment by mapron** [comment]
Some errors from clang-format, "format is not conforming to the current style" mostly on c++20 concepts. My clang verison is 15.0.7

Oops, yeah, forgot to update to recent version. 

Need to specify somehow in cmake what clang-format is set in CLANG_FORMAT_COMMAND, as every major version is incompatible .

fixed format in the main.

**Comment by mapron** [comment]
> Mernel depends on 7zip_static, but 7zip_static uses windows.h

not really depends, it just provide a target. 7zip used for win32 self-extracting archive, installer.cmake in FreeHeroes.

I added ifdef in cmake, so you should be fine for now (at least at cmake-level, not sure if clang/gcc errors persist)

**Comment by mapron** [comment]
> cmake command AddCompilerFlagIfSupported can't be found.

forgot to mention, I hope I fixed that as well.

**Comment by mapron** [comment]
>  HD Sprite is much better

sure, I also got 'great' on black background. But when you put sprite back to transparent form, you lose a lot and contours look like mess (also don't forget sprites has semi-shadows and selection regions. My png converter gave them special transparency codes as well).

**Comment by jxo** [comment]
@mapron I do a pull request on mernel and this project, to fix build on linux.
I added extra includes for addtarget, I find you have fix ed it in mernel targets.cmake

**Comment by mapron** [comment]
@jxo  please check my comments in the review.

**Comment by mapron** [comment]
@jxo  thank you for taking your time on that.

Feel free to check master branch again if something went wrong after merge.

**Comment by jxo** [comment]
@mapron ok.
what I can help for?
1. run app in linux, fix more runtime problems?
2. translations for chinese?
3. HD Sprites?

**Comment by mapron** [comment]
3 HD Sprites?
no, they will violate the copyright, no open-source project can provide them. I have HD sprites support already, technically.

**Comment by mapron** [comment]
2. if you have hota / SoD with chinise translation somehow, would be nice if you adopted translation conversion  for Chinise
https://github.com/mapron/FreeHeroes/blob/master/src/Gui/LegacyConverterUtil/LocalizationConverter.cpp#L109
https://github.com/mapron/FreeHeroes/blob/master/src/Gui/LegacyConverterUtil/LocalizationConverter.cpp#L247

If there no such distros (with LOD/lng files), not really needed translation I think.
You can add Qt ts files for zh_cn, but, I don't think is highly needed (probably loc strings will be rewritten multiple times).

So auto-conversion from SoD is all help I really need.

**Comment by mapron** [comment]
1. What app? for battle emulator it worked fine I used it while developing on linux. For other apps, most of them console, so. Not really.

You can play around with MapToolUI/MapEditor pair (latter is run from MapTool, so only MapTool is really needed). 
Some UI glitches/quirks maybe.

If you really want to do it :)

**Comment by jxo** [comment]
> 3 HD Sprites? no, they will violate the copyright, no open-source project can provide them. I have HD sprites support already, technically.

Ubi HD Version use .pak sprite format, they packed sprite on several texturesheets, and provide descriptions of every frame.
If we do not provide pak files it's ok for users who already have pak files, I don't think this will violate the copyright.
For some missing sprites in SOD, this can't be solved easily.

**Comment by mapron** [comment]
Ubi HD edition sprites you mean? Support importing them with  converter? well... I did not even think about it. At least in russian community consensus is HD edition sucks, no one ever wanted it and their 'remaster' too. But I understand some people can want to import those, yeah. 

At first I thought you suggested neural upscale sprites and provide in distro (and THAT I said is not copyright friendly, as upscaling is not enough of rework to avoid issues).

**Comment by jxo** [comment]
@mapron the Ubi HD edition game is not so good, that is made by dotemu, just want to earn quick money. But HD Resources are the same and better, ubi redraws the sprites for x2, x3 large by human, support 
transparency not replace color with palette.

**Comment by jxo** [comment]
But missing some sprites in HD edition compares to SOD, not too much

**Comment by mapron** [comment]
'not too many' are AB, SoD and HotA sprites :)  
I don't agree with ' But HD Resources are the same and better' , sorry. that is matter of taste.  What we are talking about, again? From technical perspective? 
Support import of HD edition data? Ok you can investigate that (1 . patches to my FH  project or 2 in your own project and share the parser code). That's ok, no objection on that part.

**Comment by mapron** [comment]
> drawn by community 

I saw one porject of 'redrawing' for all these years. I mean, from scratch. And that project looked awful. I believe only commercial company with a lot of money ca create good set of hand-drawn sprites, not one enthusiast.

**Comment by jxo** [comment]
![Uploading mmexport1677643884436.png…]()

**Comment by jxo** [comment]
![Uploading mmexport1677643884436.png…]()

**Comment by jxo** [comment]
![Uploading mmexport1677643884436.png…]()

**Comment by jxo** [comment]
![mmexport1677643884436](https://user-images.githubusercontent.com/1549577/222043936-3e8bfe2c-c1e9-4f2a-a04b-fccd5c24abce.png)

**Comment by jxo** [comment]
@mapron technically, supporting HD means supporting different scale factor and dealing with different screen resolution, for example support for 4K screen maybe.

**Comment by jxo** [comment]
and maybe hardcoded coordinates and sizes should not be used.

**Comment by mapron** [comment]
> , supporting HD means supporting different scale factor and dealing with different screen resolution

That already done.
Coordinates like 'position of arrow shooting' is bound to sprite json, not program code.
I already said that I tested 2x sprites upscaled with network in battle emulator. Why we are discussing this?

**Comment by mapron** [comment]
>  I have not done a research about the sprites and bitmap differences between ROE and SOD.

Depends of what you are interested in. There are several formats for RLE, most of them are from RoE already, so no difference. 
You can check this
https://github.com/mapron/FreeHeroes/blob/master/src/Gui/LegacyConverterUtil/BitmapFile.cpp#L161
for reading different sprites (well, and writing them too)

**Comment by jxo** [comment]
> > I have not done a research about the sprites and bitmap differences between ROE and SOD.
> 
> Depends of what you are interested in. There are several formats for RLE, most of them are from RoE already, so no difference. You can check this https://github.com/mapron/FreeHeroes/blob/master/src/Gui/LegacyConverterUtil/BitmapFile.cpp#L161 for reading different sprites (well, and writing them too)

Not the image compression format differences, just for missing creatures, towns, and others which in SOD but not in ROE.

**Comment by jxo** [comment]
> Some work can be improved for UI sprites, but I try to vector recnder UI anyway most of the time. (things like morale icons or skill icons can be improved for HD tho)

Maybe use SVG morale icons and skill icons.

**Comment by mapron** [comment]
I missing your point overall. What do you want :)

**Comment by jxo** [comment]
Thank you for your time and patience.
The goal of the project is very appealling.

I want nothing, just think about what to do next.

And maybe make graphics better.
This guy said in https://github.com/mapron/FreeHeroes/issues/1#issue-988597366
Export HD resources from offical, maybe the same meaning.

> Support import of HD edition data? Ok you can investigate that (1 . patches to my FH project

I will do import HD edition data next.

**Comment by mapron** [comment]
My current focus (as you see by latest git history) - is map generation; then map editor, then (probably) something like map playtest-singleplayer stuff;  several months probably I will be focused on map generator only (as it is a usable product for HotA playerbase  and have an interest today). 

So don't expect much work from me on battle emulator or adventure mode.

**Comment by jxo** [comment]
@mapron 
Is translation rework finished?
https://github.com/mapron/FreeHeroes/blob/master/src/Gui/Localization/LocalizationManager.cpp#L87

I add zh_CN, convertion is ok, but translation seems not work

**Comment by jxo** [comment]
QStandardPath::AppLocalDataLocation
in linux is username/.local/share/FreeHeroes

But Mernel AppLocations::getAppdataDir is username/FreeHeroes
 
Different resources path.

**Comment by mapron** [comment]
LocalizationManager doesn't do much atm. Probably will remove that class entirely some day.
